.codecov.yml, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE/other.md, .github/dependabot.yml, .github/labeler.yml, .github/workflows/labeler.yml, .github/workflows/lint.yml, .mergify.yml, CONTRIBUTING.md
This PR adds the support for CI
=> build: added CI support

package.json, packages/core/package.json, packages/core/src/desmosclient.ts, packages/types/package.json, packages/types/script/prepare.sh, packages/walletconnect/package.json, yarn.lock
This PR improves the DesmosClient signing method
=> feat: improve DesmosClient signing method

packages/core/src/cosmjs.ts, packages/core/src/signers/adapter.ts, packages/core/src/signers/index.ts, packages/core/src/signers/path.ts
* Expose the cosmjs `stringToPath` and `pathToString` functions;
* Adds a `makeDesmosPath` to generate a Desmos bip44 derivation path with coin type 852.
=> feat: added some utilities to mange bip44 derivation paths

.github/workflows/release.yml
This PR fixes the `release` action so that it can properly build and publish new versions of DesmJS packages each time a new tag is pushed. 
Closes: #5
---
I have...
I have...
=> build(ci): fix the release action to include Protoc installation

packages/types/package.json, yarn.lock
Update protobufjs to 7.1.0
---
I have...
I have...
=> build(deps): bump protobufjs to 7.1.0

packages/core/src/encodeobjects/cosmos.ts
This PR adds missing `authz` and `feegrant` EncodeObjects.
---
I have...
I have...
=> feat: added missing authz and feegrant EncodeObjects

CHANGELOG.md, packages/core/package.json, packages/keplr/package.json, packages/types/package.json, packages/walletconnect/package.json
Closes: #XXXX
---
I have...
I have...
=> chore: release v4.6.2

.github/dependabot.yml
Closes: #XXXX
---
I have...
I have...
=> build(ci): setup dependabot

.github/workflows/tests.yaml, .gitignore, package.json, packages/walletconnect-v2/.example.test.env, packages/walletconnect-v2/README.md, packages/walletconnect-v2/jest.config.js, packages/walletconnect-v2/package.json, packages/walletconnect-v2/src/decode.ts, packages/walletconnect-v2/src/encode.ts, packages/walletconnect-v2/src/index.ts, packages/walletconnect-v2/src/rpcrequests.ts, packages/walletconnect-v2/src/rpcresponse.ts, packages/walletconnect-v2/src/signer.ts, packages/walletconnect-v2/src/signer.unit.spec.ts, packages/walletconnect-v2/src/types.ts, packages/walletconnect-v2/test.dotenv.config.js, packages/walletconnect-v2/tsconfig.json, yarn.lock
Closes: #XXXX
This PR adds the `@desmoslabs/desmjs-walletconnect-v2` package that supports the new WalletConnect v2 APIs.
---
I have...
I have...
=> feat: add walletconnect-v2 package to support WallectConnect v2

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/tests.yaml
This PR improves the GitHub Action workflows to have better steps names and organization
---
I have...
I have...
=> build(ci): improve workflows

packages/core/src/desmosclient.ts
Closes: #XXXX
This PR adds a `querier` method to `DesmosClient` that returns an instance of `DesmosQueryClient` so that users can be able to query the data from the chain.
---
I have...
I have...
=> feat: add querier method to expose the DesmosQueryClient

packages/keplr/.eslintrc.js, packages/keplr/package.json, packages/keplr/src/chains.ts, packages/keplr/src/signer.ts, packages/keplr/tsconfig.eslint.json, yarn.lock
Closes: #XXXX
This PR fixes some lint errors, optimize the creation of the `keplr_keystorechange` listeners  and updates the features to signal the support of cosmwasm.
---
I have...
I have...
=> feat: support CosmWasm and improve keystoragechange listeners

packages/core/src/desmosclient.integration.spec.ts, packages/core/src/desmosclient.ts
Closes: #XXXX
This PR adds an `offline` method that allows to create a `DesmosClient` that can be used to sign transactions in a offline enviroment.
---
I have...
I have...
=> feat: allow to create an offline DesmosClient

packages/walletconnect-v2/package.json, packages/walletconnect-v2/src/decode.ts, packages/walletconnect-v2/src/decode.unit.spec.ts, packages/walletconnect-v2/src/types.ts, yarn.lock
This PR adds some utilty functions to decode the WalletConnect session requests.
---
I have...
I have...
=> feat: add functions to decode WalletConnect requests

packages/core/src/aminomessages/reactions/converter.ts, packages/core/src/aminomessages/reports/converter.ts, packages/core/src/desmosclient.integration.spec.ts
This PR fixes Reports and Reactions `fromAmino` converters. It also includes additional integrations tests. 
---
I have...
I have...
=> fix: fixed Reports and Reactions amino converters

.eslintrc.json, packages/walletconnect-v2/package.json, packages/walletconnect-v2/src/encode.ts, packages/walletconnect-v2/src/rpcrequests.ts, packages/walletconnect-v2/src/rpcresponse.ts, packages/walletconnect-v2/src/signer.ts, packages/walletconnect-v2/src/signer.unit.spec.ts, yarn.lock
Closes: #292 
This PR fixes the build errror arrised during the unit tests after bumping walletconnect/sign-client  to the version `2.4.0`.
---
I have...
I have...
=> fix: fix errors after bumping walletconnect/sign-client to 2.4.0

packages/core/src/desmosclient.integration.spec.ts, packages/core/src/desmosclient.ts
Closes: #XXXX
This PR updates the `DesmosClient.signTx` method signature by moving the non required params inside `SignTxOptions`.  
Depends-On: #299 
---
I have...
I have...
=> refactor!: better signtx signature

CHANGELOG.md, packages/core/package.json, packages/keplr/package.json, packages/types/package.json, packages/walletconnect-v2/package.json, packages/walletconnect/package.json, packages/web3auth-mobile/package.json, packages/web3auth-web/package.json
Closes: #XXXX
In anticipation of releasing version `v4.7.8`, this PR includes updates to both the CHANGELOG.md and the package versions.
---
I have...
I have...
=> chore: prepare to release v4.7.8

packages/core/src/const/cosmos/staking/index.ts
Closes: #XXXX
This PR fixes the protobuf type url of the type `StakeAuthorization`.
---
I have...
I have...
=> fix: fix StakeAuthorizationTypeUrl

packages/core/src/aminomessages/cosmos/authz/converter.ts
Closes: #XXXX
`new Date` accepts millisecond instead of second
Also `.000` in the ISO format needs to be removed
---
I have...
I have...
=> fix: authz expiration amino conversion

packages/core/src/const/cosmos/gov/index.ts
Closes: #XXXX
This PR fixes the type url of all the x/gov messages
---
I have...
I have...
=> fix: fix x/gov messages type url

CHANGELOG.md, packages/core/package.json, packages/keplr/package.json, packages/types/package.json, packages/walletconnect-v2/package.json, packages/walletconnect/package.json, packages/web3auth-mobile/package.json, packages/web3auth-web/package.json
Closes: #XXXX
---
I have...
I have...
=> chore: release v5.0.1

docs/docs/packages/web3auth-web.md, docs/package.json, packages/web3auth-web/package.json, packages/web3auth-web/src/web3auth-ui.d.ts, yarn.lock
Closes: SDK-17
Closes: #608
---
I have...
I have...
=> build(deps): bump @web3auth/modal from 5.2.1 to 6.1.1 and @web3auth/ui from 5.2.0 to 6.1.1

CHANGELOG.md, packages/core/README.md, packages/core/package.json, packages/keplr/package.json, packages/types/package.json, packages/walletconnect-v2/package.json, packages/web3auth-mobile/package.json, packages/web3auth-web/package.json
Closes: #XXXX
---
I have...
I have...
=> chore: release v5.1.0

docs/docs/packages/walletconnect-v2.md, docs/docs/packages/web3auth-mobile.mdx, docs/docs/perform-transactions.md, docs/docs/query-data.md, packages/web3auth-mobile/src/index.ts
Closes: #XXXX
This PR updates:
1. The objects exported from `@desmoslabs/desmjs-web3auth-mobile` adding what exports the `@web3auth/react-native-sdk` package;
2. The documentation related to the  `@desmoslabs/desmjs-web3auth-mobile` package.
---
I have...
I have...
=> chore: export web3auth and fix examples

CHANGELOG.md, packages/core/package.json, packages/keplr/package.json, packages/types/package.json, packages/walletconnect-v2/package.json, packages/web3auth-mobile/package.json, packages/web3auth-web/package.json
Closes: #XXXX
---
I have...
I have...
=> chore: release v5.1.1

CHANGELOG.md, packages/core/README.md, packages/core/package.json, packages/keplr/README.md, packages/keplr/package.json, packages/types/package.json, packages/walletconnect-v2/README.md, packages/walletconnect-v2/package.json, packages/web3auth-mobile/README.md, packages/web3auth-mobile/package.json, packages/web3auth-web/README.md, packages/web3auth-web/package.json
Closes: #XXXX
---
I have...
I have...
=> chore: prepare to release v6.0.0
